#!/bin/bash
ROOT_PWD=${PWD}

rm app.tar.gz
rm -rf ${ROOT_PWD}/tmp
mkdir -p ${ROOT_PWD}/tmp

docker run --rm -v ${ROOT_PWD}/tmp:/host -v ${ROOT_PWD}/compose/build_app:/build_app -v ${ROOT_PWD}/rails-webapp:/opt/cc/app artifactory.roving.com/social/rails:${VERSION} /build_app

tar -czf app.tar.gz -C ${ROOT_PWD}/tmp . -C ${ROOT_PWD}/compose .
rm -rf ${ROOT_PWD}/tmp
