rails:
  extends:
    file: compose/common.yml
    service: rails
  environment:
    - ENV_NAME=D1
    - ENV_CLASS=DEV
    - LOCATION_LDAP_VAULT=ldaps://p2-qaldapvault.ad.prodcc.net
  ports:
    - "1337:80"
