#!/bin/bash
set -e

#########
## This file contains examples of build glue code.
## Modify these examples to meet your needs
#########

ROOT_PWD=$PWD
export DOCKER_HOST=tcp://p2-docker01.ad.prodcc.net:4243

#######################
## RUBY
#######################
gem install bundler

# Bundle Assets
bundle install -j4
export BASE_VERSION=`rake version`
./bootstrap
