#!/bin/bash
set -e

#########
## This file contains examples of build glue code.
## Modify these examples to meet your needs
#########

ROOT_PWD=$PWD

export DOCKER_HOST=tcp://p2-docker01.ad.prodcc.net:4243

BASE_VERSION=`rake version`
echo "Uploading ${BASE_VERSION}"
docker push artifactory.roving.com/social/rails:${BASE_VERSION}

rake bump['--minor']
